#!/usr/bin/env bash
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080
#You cannot use apt-get remove
#Write a Bash script that configures the container to fit the above requirements
sudo chmod -R 755 /etc/nginx/
sudo pkill -9 apache2
sudo sed -i 's/8080/8081/g' /etc/apache2/ports.conf
sudo service apache2 restart
su nginx -c "sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default"
su nginx service nginx restart
