#!/usr/bin/env bash
#this program installs inginx on my web server

ssh -i ~/.ssh/school -T ubuntu@34.229.125.55 << 'EOSSH'
sudo apt update
sudo apt install nginx -y

sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'
sudo /etc/init.d/nginx restart
sudo service nginx restart

#this command will create a symbolic link between the file /etc/nginx/sites-available/default and /etc/nginx/sites-enabled/default
sudo update-rc.d -f nginx defaultis
sudo /etc/init.d/nginx status

EOSSH
