#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update -y && sudo apt-get upgrade -y

sudo apt-get install nginx -y

echo "Holberton School" | sudo tee /var/www/html/index.html

echo "
events {

}

http {
	server {
		listen 80;

		root /var/www/html;

		location /redirect_me {
			return 301 https://google.com;
		}
	}
}" | sudo tee /etc/nginx/nginx.conf

sudo service nginx restart

